# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PulsarApi.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("PulsarApi.proto", :syntax => :proto2) do
    add_message "pulsar.proto.Schema" do
      required :name, :string, 1
      required :schema_data, :bytes, 3
      required :type, :enum, 4, "pulsar.proto.Schema.Type"
      repeated :properties, :message, 5, "pulsar.proto.KeyValue"
    end
    add_enum "pulsar.proto.Schema.Type" do
      value :None, 0
      value :String, 1
      value :Json, 2
      value :Protobuf, 3
      value :Avro, 4
      value :Bool, 5
      value :Int8, 6
      value :Int16, 7
      value :Int32, 8
      value :Int64, 9
      value :Float, 10
      value :Double, 11
      value :Date, 12
      value :Time, 13
      value :Timestamp, 14
      value :KeyValue, 15
    end
    add_message "pulsar.proto.MessageIdData" do
      required :ledgerId, :uint64, 1
      required :entryId, :uint64, 2
      optional :partition, :int32, 3, default: -1
      optional :batch_index, :int32, 4, default: -1
    end
    add_message "pulsar.proto.KeyValue" do
      required :key, :string, 1
      required :value, :string, 2
    end
    add_message "pulsar.proto.KeyLongValue" do
      required :key, :string, 1
      required :value, :uint64, 2
    end
    add_message "pulsar.proto.EncryptionKeys" do
      required :key, :string, 1
      required :value, :bytes, 2
      repeated :metadata, :message, 3, "pulsar.proto.KeyValue"
    end
    add_message "pulsar.proto.MessageMetadata" do
      required :producer_name, :string, 1
      required :sequence_id, :uint64, 2
      required :publish_time, :uint64, 3
      repeated :properties, :message, 4, "pulsar.proto.KeyValue"
      optional :replicated_from, :string, 5
      optional :partition_key, :string, 6
      repeated :replicate_to, :string, 7
      optional :compression, :enum, 8, "pulsar.proto.CompressionType", default: 0
      optional :uncompressed_size, :uint32, 9, default: 0
      optional :num_messages_in_batch, :int32, 11, default: 1
      optional :event_time, :uint64, 12, default: 0
      repeated :encryption_keys, :message, 13, "pulsar.proto.EncryptionKeys"
      optional :encryption_algo, :string, 14
      optional :encryption_param, :bytes, 15
      optional :schema_version, :bytes, 16
      optional :partition_key_b64_encoded, :bool, 17, default: false
      optional :ordering_key, :bytes, 18
      optional :deliver_at_time, :int64, 19
      optional :marker_type, :int32, 20
      optional :txnid_least_bits, :uint64, 22, default: 0
      optional :txnid_most_bits, :uint64, 23, default: 0
    end
    add_message "pulsar.proto.SingleMessageMetadata" do
      repeated :properties, :message, 1, "pulsar.proto.KeyValue"
      optional :partition_key, :string, 2
      required :payload_size, :int32, 3
      optional :compacted_out, :bool, 4, default: false
      optional :event_time, :uint64, 5, default: 0
      optional :partition_key_b64_encoded, :bool, 6, default: false
      optional :ordering_key, :bytes, 7
      optional :sequence_id, :uint64, 8
    end
    add_message "pulsar.proto.CommandConnect" do
      required :client_version, :string, 1
      optional :auth_method, :enum, 2, "pulsar.proto.AuthMethod"
      optional :auth_method_name, :string, 5
      optional :auth_data, :bytes, 3
      optional :protocol_version, :int32, 4, default: 0
      optional :proxy_to_broker_url, :string, 6
      optional :original_principal, :string, 7
      optional :original_auth_data, :string, 8
      optional :original_auth_method, :string, 9
    end
    add_message "pulsar.proto.CommandConnected" do
      required :server_version, :string, 1
      optional :protocol_version, :int32, 2, default: 0
      optional :max_message_size, :int32, 3
    end
    add_message "pulsar.proto.CommandAuthResponse" do
      optional :client_version, :string, 1
      optional :response, :message, 2, "pulsar.proto.AuthData"
      optional :protocol_version, :int32, 3, default: 0
    end
    add_message "pulsar.proto.CommandAuthChallenge" do
      optional :server_version, :string, 1
      optional :challenge, :message, 2, "pulsar.proto.AuthData"
      optional :protocol_version, :int32, 3, default: 0
    end
    add_message "pulsar.proto.AuthData" do
      optional :auth_method_name, :string, 1
      optional :auth_data, :bytes, 2
    end
    add_message "pulsar.proto.CommandSubscribe" do
      required :topic, :string, 1
      required :subscription, :string, 2
      required :subType, :enum, 3, "pulsar.proto.CommandSubscribe.SubType"
      required :consumer_id, :uint64, 4
      required :request_id, :uint64, 5
      optional :consumer_name, :string, 6
      optional :priority_level, :int32, 7
      optional :durable, :bool, 8, default: true
      optional :start_message_id, :message, 9, "pulsar.proto.MessageIdData"
      repeated :metadata, :message, 10, "pulsar.proto.KeyValue"
      optional :read_compacted, :bool, 11
      optional :schema, :message, 12, "pulsar.proto.Schema"
      optional :initialPosition, :enum, 13, "pulsar.proto.CommandSubscribe.InitialPosition", default: 0
      optional :replicate_subscription_state, :bool, 14
      optional :force_topic_creation, :bool, 15, default: true
      optional :start_message_rollback_duration_sec, :uint64, 16, default: 0
    end
    add_enum "pulsar.proto.CommandSubscribe.SubType" do
      value :Exclusive, 0
      value :Shared, 1
      value :Failover, 2
      value :Key_Shared, 3
    end
    add_enum "pulsar.proto.CommandSubscribe.InitialPosition" do
      value :Latest, 0
      value :Earliest, 1
    end
    add_message "pulsar.proto.CommandPartitionedTopicMetadata" do
      required :topic, :string, 1
      required :request_id, :uint64, 2
      optional :original_principal, :string, 3
      optional :original_auth_data, :string, 4
      optional :original_auth_method, :string, 5
    end
    add_message "pulsar.proto.CommandPartitionedTopicMetadataResponse" do
      optional :partitions, :uint32, 1
      required :request_id, :uint64, 2
      optional :response, :enum, 3, "pulsar.proto.CommandPartitionedTopicMetadataResponse.LookupType"
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_enum "pulsar.proto.CommandPartitionedTopicMetadataResponse.LookupType" do
      value :Success, 0
      value :Failed, 1
    end
    add_message "pulsar.proto.CommandLookupTopic" do
      required :topic, :string, 1
      required :request_id, :uint64, 2
      optional :authoritative, :bool, 3, default: false
      optional :original_principal, :string, 4
      optional :original_auth_data, :string, 5
      optional :original_auth_method, :string, 6
    end
    add_message "pulsar.proto.CommandLookupTopicResponse" do
      optional :brokerServiceUrl, :string, 1
      optional :brokerServiceUrlTls, :string, 2
      optional :response, :enum, 3, "pulsar.proto.CommandLookupTopicResponse.LookupType"
      required :request_id, :uint64, 4
      optional :authoritative, :bool, 5, default: false
      optional :error, :enum, 6, "pulsar.proto.ServerError"
      optional :message, :string, 7
      optional :proxy_through_service_url, :bool, 8, default: false
    end
    add_enum "pulsar.proto.CommandLookupTopicResponse.LookupType" do
      value :Redirect, 0
      value :Connect, 1
      value :Failed, 2
    end
    add_message "pulsar.proto.CommandProducer" do
      required :topic, :string, 1
      required :producer_id, :uint64, 2
      required :request_id, :uint64, 3
      optional :producer_name, :string, 4
      optional :encrypted, :bool, 5, default: false
      repeated :metadata, :message, 6, "pulsar.proto.KeyValue"
      optional :schema, :message, 7, "pulsar.proto.Schema"
    end
    add_message "pulsar.proto.CommandSend" do
      required :producer_id, :uint64, 1
      required :sequence_id, :uint64, 2
      optional :num_messages, :int32, 3, default: 1
      optional :txnid_least_bits, :uint64, 4, default: 0
      optional :txnid_most_bits, :uint64, 5, default: 0
    end
    add_message "pulsar.proto.CommandSendReceipt" do
      required :producer_id, :uint64, 1
      required :sequence_id, :uint64, 2
      optional :message_id, :message, 3, "pulsar.proto.MessageIdData"
    end
    add_message "pulsar.proto.CommandSendError" do
      required :producer_id, :uint64, 1
      required :sequence_id, :uint64, 2
      required :error, :enum, 3, "pulsar.proto.ServerError"
      required :message, :string, 4
    end
    add_message "pulsar.proto.CommandMessage" do
      required :consumer_id, :uint64, 1
      required :message_id, :message, 2, "pulsar.proto.MessageIdData"
      optional :redelivery_count, :uint32, 3, default: 0
    end
    add_message "pulsar.proto.CommandAck" do
      required :consumer_id, :uint64, 1
      required :ack_type, :enum, 2, "pulsar.proto.CommandAck.AckType"
      repeated :message_id, :message, 3, "pulsar.proto.MessageIdData"
      optional :validation_error, :enum, 4, "pulsar.proto.CommandAck.ValidationError"
      repeated :properties, :message, 5, "pulsar.proto.KeyLongValue"
      optional :txnid_least_bits, :uint64, 6, default: 0
      optional :txnid_most_bits, :uint64, 7, default: 0
    end
    add_enum "pulsar.proto.CommandAck.AckType" do
      value :Individual, 0
      value :Cumulative, 1
    end
    add_enum "pulsar.proto.CommandAck.ValidationError" do
      value :UncompressedSizeCorruption, 0
      value :DecompressionError, 1
      value :ChecksumMismatch, 2
      value :BatchDeSerializeError, 3
      value :DecryptionError, 4
    end
    add_message "pulsar.proto.CommandAckResponse" do
      required :consumer_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_message "pulsar.proto.CommandActiveConsumerChange" do
      required :consumer_id, :uint64, 1
      optional :is_active, :bool, 2, default: false
    end
    add_message "pulsar.proto.CommandFlow" do
      required :consumer_id, :uint64, 1
      required :messagePermits, :uint32, 2
    end
    add_message "pulsar.proto.CommandUnsubscribe" do
      required :consumer_id, :uint64, 1
      required :request_id, :uint64, 2
    end
    add_message "pulsar.proto.CommandSeek" do
      required :consumer_id, :uint64, 1
      required :request_id, :uint64, 2
      optional :message_id, :message, 3, "pulsar.proto.MessageIdData"
      optional :message_publish_time, :uint64, 4
    end
    add_message "pulsar.proto.CommandReachedEndOfTopic" do
      required :consumer_id, :uint64, 1
    end
    add_message "pulsar.proto.CommandCloseProducer" do
      required :producer_id, :uint64, 1
      required :request_id, :uint64, 2
    end
    add_message "pulsar.proto.CommandCloseConsumer" do
      required :consumer_id, :uint64, 1
      required :request_id, :uint64, 2
    end
    add_message "pulsar.proto.CommandRedeliverUnacknowledgedMessages" do
      required :consumer_id, :uint64, 1
      repeated :message_ids, :message, 2, "pulsar.proto.MessageIdData"
    end
    add_message "pulsar.proto.CommandSuccess" do
      required :request_id, :uint64, 1
      optional :schema, :message, 2, "pulsar.proto.Schema"
    end
    add_message "pulsar.proto.CommandProducerSuccess" do
      required :request_id, :uint64, 1
      required :producer_name, :string, 2
      optional :last_sequence_id, :int64, 3, default: -1
      optional :schema_version, :bytes, 4
    end
    add_message "pulsar.proto.CommandError" do
      required :request_id, :uint64, 1
      required :error, :enum, 2, "pulsar.proto.ServerError"
      required :message, :string, 3
    end
    add_message "pulsar.proto.CommandPing" do
    end
    add_message "pulsar.proto.CommandPong" do
    end
    add_message "pulsar.proto.CommandConsumerStats" do
      required :request_id, :uint64, 1
      required :consumer_id, :uint64, 4
    end
    add_message "pulsar.proto.CommandConsumerStatsResponse" do
      required :request_id, :uint64, 1
      optional :error_code, :enum, 2, "pulsar.proto.ServerError"
      optional :error_message, :string, 3
      optional :msgRateOut, :double, 4
      optional :msgThroughputOut, :double, 5
      optional :msgRateRedeliver, :double, 6
      optional :consumerName, :string, 7
      optional :availablePermits, :uint64, 8
      optional :unackedMessages, :uint64, 9
      optional :blockedConsumerOnUnackedMsgs, :bool, 10
      optional :address, :string, 11
      optional :connectedSince, :string, 12
      optional :type, :string, 13
      optional :msgRateExpired, :double, 14
      optional :msgBacklog, :uint64, 15
    end
    add_message "pulsar.proto.CommandGetLastMessageId" do
      required :consumer_id, :uint64, 1
      required :request_id, :uint64, 2
    end
    add_message "pulsar.proto.CommandGetLastMessageIdResponse" do
      required :last_message_id, :message, 1, "pulsar.proto.MessageIdData"
      required :request_id, :uint64, 2
    end
    add_message "pulsar.proto.CommandGetTopicsOfNamespace" do
      required :request_id, :uint64, 1
      required :namespace, :string, 2
      optional :mode, :enum, 3, "pulsar.proto.CommandGetTopicsOfNamespace.Mode", default: 0
    end
    add_enum "pulsar.proto.CommandGetTopicsOfNamespace.Mode" do
      value :PERSISTENT, 0
      value :NON_PERSISTENT, 1
      value :ALL, 2
    end
    add_message "pulsar.proto.CommandGetTopicsOfNamespaceResponse" do
      required :request_id, :uint64, 1
      repeated :topics, :string, 2
    end
    add_message "pulsar.proto.CommandGetSchema" do
      required :request_id, :uint64, 1
      required :topic, :string, 2
      optional :schema_version, :bytes, 3
    end
    add_message "pulsar.proto.CommandGetSchemaResponse" do
      required :request_id, :uint64, 1
      optional :error_code, :enum, 2, "pulsar.proto.ServerError"
      optional :error_message, :string, 3
      optional :schema, :message, 4, "pulsar.proto.Schema"
      optional :schema_version, :bytes, 5
    end
    add_message "pulsar.proto.CommandGetOrCreateSchema" do
      required :request_id, :uint64, 1
      required :topic, :string, 2
      required :schema, :message, 3, "pulsar.proto.Schema"
    end
    add_message "pulsar.proto.CommandGetOrCreateSchemaResponse" do
      required :request_id, :uint64, 1
      optional :error_code, :enum, 2, "pulsar.proto.ServerError"
      optional :error_message, :string, 3
      optional :schema_version, :bytes, 4
    end
    add_message "pulsar.proto.CommandNewTxn" do
      required :request_id, :uint64, 1
      optional :txn_ttl_seconds, :uint64, 2, default: 0
    end
    add_message "pulsar.proto.CommandNewTxnResponse" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_message "pulsar.proto.CommandAddPartitionToTxn" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      repeated :partitions, :string, 4
    end
    add_message "pulsar.proto.CommandAddPartitionToTxnResponse" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_message "pulsar.proto.Subscription" do
      required :topic, :string, 1
      required :subscription, :string, 2
    end
    add_message "pulsar.proto.CommandAddSubscriptionToTxn" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      repeated :subscription, :message, 4, "pulsar.proto.Subscription"
    end
    add_message "pulsar.proto.CommandAddSubscriptionToTxnResponse" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_message "pulsar.proto.CommandEndTxn" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :txn_action, :enum, 4, "pulsar.proto.TxnAction"
    end
    add_message "pulsar.proto.CommandEndTxnResponse" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_message "pulsar.proto.CommandEndTxnOnPartition" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :topic, :string, 4
      optional :txn_action, :enum, 5, "pulsar.proto.TxnAction"
    end
    add_message "pulsar.proto.CommandEndTxnOnPartitionResponse" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_message "pulsar.proto.CommandEndTxnOnSubscription" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :subscription, :message, 4, "pulsar.proto.Subscription"
      optional :txn_action, :enum, 5, "pulsar.proto.TxnAction"
    end
    add_message "pulsar.proto.CommandEndTxnOnSubscriptionResponse" do
      required :request_id, :uint64, 1
      optional :txnid_least_bits, :uint64, 2, default: 0
      optional :txnid_most_bits, :uint64, 3, default: 0
      optional :error, :enum, 4, "pulsar.proto.ServerError"
      optional :message, :string, 5
    end
    add_message "pulsar.proto.BaseCommand" do
      required :type, :enum, 1, "pulsar.proto.BaseCommand.Type"
      optional :connect, :message, 2, "pulsar.proto.CommandConnect"
      optional :connected, :message, 3, "pulsar.proto.CommandConnected"
      optional :subscribe, :message, 4, "pulsar.proto.CommandSubscribe"
      optional :producer, :message, 5, "pulsar.proto.CommandProducer"
      optional :send, :message, 6, "pulsar.proto.CommandSend"
      optional :send_receipt, :message, 7, "pulsar.proto.CommandSendReceipt"
      optional :send_error, :message, 8, "pulsar.proto.CommandSendError"
      optional :message, :message, 9, "pulsar.proto.CommandMessage"
      optional :ack, :message, 10, "pulsar.proto.CommandAck"
      optional :flow, :message, 11, "pulsar.proto.CommandFlow"
      optional :unsubscribe, :message, 12, "pulsar.proto.CommandUnsubscribe"
      optional :success, :message, 13, "pulsar.proto.CommandSuccess"
      optional :error, :message, 14, "pulsar.proto.CommandError"
      optional :close_producer, :message, 15, "pulsar.proto.CommandCloseProducer"
      optional :close_consumer, :message, 16, "pulsar.proto.CommandCloseConsumer"
      optional :producer_success, :message, 17, "pulsar.proto.CommandProducerSuccess"
      optional :ping, :message, 18, "pulsar.proto.CommandPing"
      optional :pong, :message, 19, "pulsar.proto.CommandPong"
      optional :redeliverUnacknowledgedMessages, :message, 20, "pulsar.proto.CommandRedeliverUnacknowledgedMessages"
      optional :partitionMetadata, :message, 21, "pulsar.proto.CommandPartitionedTopicMetadata"
      optional :partitionMetadataResponse, :message, 22, "pulsar.proto.CommandPartitionedTopicMetadataResponse"
      optional :lookupTopic, :message, 23, "pulsar.proto.CommandLookupTopic"
      optional :lookupTopicResponse, :message, 24, "pulsar.proto.CommandLookupTopicResponse"
      optional :consumerStats, :message, 25, "pulsar.proto.CommandConsumerStats"
      optional :consumerStatsResponse, :message, 26, "pulsar.proto.CommandConsumerStatsResponse"
      optional :reachedEndOfTopic, :message, 27, "pulsar.proto.CommandReachedEndOfTopic"
      optional :seek, :message, 28, "pulsar.proto.CommandSeek"
      optional :getLastMessageId, :message, 29, "pulsar.proto.CommandGetLastMessageId"
      optional :getLastMessageIdResponse, :message, 30, "pulsar.proto.CommandGetLastMessageIdResponse"
      optional :active_consumer_change, :message, 31, "pulsar.proto.CommandActiveConsumerChange"
      optional :getTopicsOfNamespace, :message, 32, "pulsar.proto.CommandGetTopicsOfNamespace"
      optional :getTopicsOfNamespaceResponse, :message, 33, "pulsar.proto.CommandGetTopicsOfNamespaceResponse"
      optional :getSchema, :message, 34, "pulsar.proto.CommandGetSchema"
      optional :getSchemaResponse, :message, 35, "pulsar.proto.CommandGetSchemaResponse"
      optional :authChallenge, :message, 36, "pulsar.proto.CommandAuthChallenge"
      optional :authResponse, :message, 37, "pulsar.proto.CommandAuthResponse"
      optional :ackResponse, :message, 38, "pulsar.proto.CommandAckResponse"
      optional :getOrCreateSchema, :message, 39, "pulsar.proto.CommandGetOrCreateSchema"
      optional :getOrCreateSchemaResponse, :message, 40, "pulsar.proto.CommandGetOrCreateSchemaResponse"
      optional :newTxn, :message, 50, "pulsar.proto.CommandNewTxn"
      optional :newTxnResponse, :message, 51, "pulsar.proto.CommandNewTxnResponse"
      optional :addPartitionToTxn, :message, 52, "pulsar.proto.CommandAddPartitionToTxn"
      optional :addPartitionToTxnResponse, :message, 53, "pulsar.proto.CommandAddPartitionToTxnResponse"
      optional :addSubscriptionToTxn, :message, 54, "pulsar.proto.CommandAddSubscriptionToTxn"
      optional :addSubscriptionToTxnResponse, :message, 55, "pulsar.proto.CommandAddSubscriptionToTxnResponse"
      optional :endTxn, :message, 56, "pulsar.proto.CommandEndTxn"
      optional :endTxnResponse, :message, 57, "pulsar.proto.CommandEndTxnResponse"
      optional :endTxnOnPartition, :message, 58, "pulsar.proto.CommandEndTxnOnPartition"
      optional :endTxnOnPartitionResponse, :message, 59, "pulsar.proto.CommandEndTxnOnPartitionResponse"
      optional :endTxnOnSubscription, :message, 60, "pulsar.proto.CommandEndTxnOnSubscription"
      optional :endTxnOnSubscriptionResponse, :message, 61, "pulsar.proto.CommandEndTxnOnSubscriptionResponse"
    end
    add_enum "pulsar.proto.BaseCommand.Type" do
      value :CONNECT, 2
      value :CONNECTED, 3
      value :SUBSCRIBE, 4
      value :PRODUCER, 5
      value :SEND, 6
      value :SEND_RECEIPT, 7
      value :SEND_ERROR, 8
      value :MESSAGE, 9
      value :ACK, 10
      value :FLOW, 11
      value :UNSUBSCRIBE, 12
      value :SUCCESS, 13
      value :ERROR, 14
      value :CLOSE_PRODUCER, 15
      value :CLOSE_CONSUMER, 16
      value :PRODUCER_SUCCESS, 17
      value :PING, 18
      value :PONG, 19
      value :REDELIVER_UNACKNOWLEDGED_MESSAGES, 20
      value :PARTITIONED_METADATA, 21
      value :PARTITIONED_METADATA_RESPONSE, 22
      value :LOOKUP, 23
      value :LOOKUP_RESPONSE, 24
      value :CONSUMER_STATS, 25
      value :CONSUMER_STATS_RESPONSE, 26
      value :REACHED_END_OF_TOPIC, 27
      value :SEEK, 28
      value :GET_LAST_MESSAGE_ID, 29
      value :GET_LAST_MESSAGE_ID_RESPONSE, 30
      value :ACTIVE_CONSUMER_CHANGE, 31
      value :GET_TOPICS_OF_NAMESPACE, 32
      value :GET_TOPICS_OF_NAMESPACE_RESPONSE, 33
      value :GET_SCHEMA, 34
      value :GET_SCHEMA_RESPONSE, 35
      value :AUTH_CHALLENGE, 36
      value :AUTH_RESPONSE, 37
      value :ACK_RESPONSE, 38
      value :GET_OR_CREATE_SCHEMA, 39
      value :GET_OR_CREATE_SCHEMA_RESPONSE, 40
      value :NEW_TXN, 50
      value :NEW_TXN_RESPONSE, 51
      value :ADD_PARTITION_TO_TXN, 52
      value :ADD_PARTITION_TO_TXN_RESPONSE, 53
      value :ADD_SUBSCRIPTION_TO_TXN, 54
      value :ADD_SUBSCRIPTION_TO_TXN_RESPONSE, 55
      value :END_TXN, 56
      value :END_TXN_RESPONSE, 57
      value :END_TXN_ON_PARTITION, 58
      value :END_TXN_ON_PARTITION_RESPONSE, 59
      value :END_TXN_ON_SUBSCRIPTION, 60
      value :END_TXN_ON_SUBSCRIPTION_RESPONSE, 61
    end
    add_enum "pulsar.proto.CompressionType" do
      value :NONE, 0
      value :LZ4, 1
      value :ZLIB, 2
      value :ZSTD, 3
      value :SNAPPY, 4
    end
    add_enum "pulsar.proto.ServerError" do
      value :UnknownError, 0
      value :MetadataError, 1
      value :PersistenceError, 2
      value :AuthenticationError, 3
      value :AuthorizationError, 4
      value :ConsumerBusy, 5
      value :ServiceNotReady, 6
      value :ProducerBlockedQuotaExceededError, 7
      value :ProducerBlockedQuotaExceededException, 8
      value :ChecksumError, 9
      value :UnsupportedVersionError, 10
      value :TopicNotFound, 11
      value :SubscriptionNotFound, 12
      value :ConsumerNotFound, 13
      value :TooManyRequests, 14
      value :TopicTerminatedError, 15
      value :ProducerBusy, 16
      value :InvalidTopicName, 17
      value :IncompatibleSchema, 18
      value :ConsumerAssignError, 19
    end
    add_enum "pulsar.proto.AuthMethod" do
      value :AuthMethodNone, 0
      value :AuthMethodYcaV1, 1
      value :AuthMethodAthens, 2
    end
    add_enum "pulsar.proto.ProtocolVersion" do
      value :v0, 0
      value :v1, 1
      value :v2, 2
      value :v3, 3
      value :v4, 4
      value :v5, 5
      value :v6, 6
      value :v7, 7
      value :v8, 8
      value :v9, 9
      value :v10, 10
      value :v11, 11
      value :v12, 12
      value :v13, 13
      value :v14, 14
      value :v15, 15
    end
    add_enum "pulsar.proto.TxnAction" do
      value :COMMIT, 0
      value :ABORT, 1
    end
  end
end

module Pulsar
  module Proto
    Schema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.Schema").msgclass
    Schema::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.Schema.Type").enummodule
    MessageIdData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.MessageIdData").msgclass
    KeyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.KeyValue").msgclass
    KeyLongValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.KeyLongValue").msgclass
    EncryptionKeys = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.EncryptionKeys").msgclass
    MessageMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.MessageMetadata").msgclass
    SingleMessageMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.SingleMessageMetadata").msgclass
    CommandConnect = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandConnect").msgclass
    CommandConnected = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandConnected").msgclass
    CommandAuthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAuthResponse").msgclass
    CommandAuthChallenge = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAuthChallenge").msgclass
    AuthData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.AuthData").msgclass
    CommandSubscribe = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSubscribe").msgclass
    CommandSubscribe::SubType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSubscribe.SubType").enummodule
    CommandSubscribe::InitialPosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSubscribe.InitialPosition").enummodule
    CommandPartitionedTopicMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandPartitionedTopicMetadata").msgclass
    CommandPartitionedTopicMetadataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandPartitionedTopicMetadataResponse").msgclass
    CommandPartitionedTopicMetadataResponse::LookupType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandPartitionedTopicMetadataResponse.LookupType").enummodule
    CommandLookupTopic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandLookupTopic").msgclass
    CommandLookupTopicResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandLookupTopicResponse").msgclass
    CommandLookupTopicResponse::LookupType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandLookupTopicResponse.LookupType").enummodule
    CommandProducer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandProducer").msgclass
    CommandSend = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSend").msgclass
    CommandSendReceipt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSendReceipt").msgclass
    CommandSendError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSendError").msgclass
    CommandMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandMessage").msgclass
    CommandAck = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAck").msgclass
    CommandAck::AckType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAck.AckType").enummodule
    CommandAck::ValidationError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAck.ValidationError").enummodule
    CommandAckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAckResponse").msgclass
    CommandActiveConsumerChange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandActiveConsumerChange").msgclass
    CommandFlow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandFlow").msgclass
    CommandUnsubscribe = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandUnsubscribe").msgclass
    CommandSeek = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSeek").msgclass
    CommandReachedEndOfTopic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandReachedEndOfTopic").msgclass
    CommandCloseProducer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandCloseProducer").msgclass
    CommandCloseConsumer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandCloseConsumer").msgclass
    CommandRedeliverUnacknowledgedMessages = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandRedeliverUnacknowledgedMessages").msgclass
    CommandSuccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandSuccess").msgclass
    CommandProducerSuccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandProducerSuccess").msgclass
    CommandError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandError").msgclass
    CommandPing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandPing").msgclass
    CommandPong = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandPong").msgclass
    CommandConsumerStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandConsumerStats").msgclass
    CommandConsumerStatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandConsumerStatsResponse").msgclass
    CommandGetLastMessageId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetLastMessageId").msgclass
    CommandGetLastMessageIdResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetLastMessageIdResponse").msgclass
    CommandGetTopicsOfNamespace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetTopicsOfNamespace").msgclass
    CommandGetTopicsOfNamespace::Mode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetTopicsOfNamespace.Mode").enummodule
    CommandGetTopicsOfNamespaceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetTopicsOfNamespaceResponse").msgclass
    CommandGetSchema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetSchema").msgclass
    CommandGetSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetSchemaResponse").msgclass
    CommandGetOrCreateSchema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetOrCreateSchema").msgclass
    CommandGetOrCreateSchemaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandGetOrCreateSchemaResponse").msgclass
    CommandNewTxn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandNewTxn").msgclass
    CommandNewTxnResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandNewTxnResponse").msgclass
    CommandAddPartitionToTxn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAddPartitionToTxn").msgclass
    CommandAddPartitionToTxnResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAddPartitionToTxnResponse").msgclass
    Subscription = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.Subscription").msgclass
    CommandAddSubscriptionToTxn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAddSubscriptionToTxn").msgclass
    CommandAddSubscriptionToTxnResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandAddSubscriptionToTxnResponse").msgclass
    CommandEndTxn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandEndTxn").msgclass
    CommandEndTxnResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandEndTxnResponse").msgclass
    CommandEndTxnOnPartition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandEndTxnOnPartition").msgclass
    CommandEndTxnOnPartitionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandEndTxnOnPartitionResponse").msgclass
    CommandEndTxnOnSubscription = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandEndTxnOnSubscription").msgclass
    CommandEndTxnOnSubscriptionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CommandEndTxnOnSubscriptionResponse").msgclass
    BaseCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.BaseCommand").msgclass
    BaseCommand::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.BaseCommand.Type").enummodule
    CompressionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.CompressionType").enummodule
    ServerError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.ServerError").enummodule
    AuthMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.AuthMethod").enummodule
    ProtocolVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.ProtocolVersion").enummodule
    TxnAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pulsar.proto.TxnAction").enummodule
  end
end
